/*  This file is part of the 'AutoScheme' project.
 *  Copyright 2021 Steven Wiley <s.wiley@katchitek.com> 
 *  SPDX-License-Identifier: BSD-2-Clause
 */
#include "autoscheme.h"
pointer LOAD_MODULE__auto_scheme_list(pointer environment);
pointer LOAD_MODULE__auto_scheme_list(pointer environment)
{
pointer return_value = T;
return_value = autoscheme_eval(cons(mk_symbol("define-library"),cons(cons(mk_symbol("auto"),cons(mk_symbol("scheme"),cons(mk_symbol("list"),NIL))),cons(cons(mk_symbol("import"),cons(cons(mk_symbol("auto"),cons(mk_symbol("scheme"),cons(mk_symbol("base"),NIL))),NIL)),cons(cons(mk_symbol("export"),cons(mk_symbol("alist-delete"),cons(mk_symbol("alist-delete!"),cons(mk_symbol("last-pair"),NIL)))),cons(cons(mk_symbol("begin"),cons(cons(mk_symbol("define"),cons(mk_symbol("alist-delete"),cons(cons(mk_symbol("lambda"),cons(cons(mk_symbol("alist"),cons(mk_symbol("key"),NIL)),cons(cons(mk_symbol("cond"),cons(cons(cons(mk_symbol("null?"),cons(mk_symbol("alist"),NIL)),cons(cons( mk_symbol("quote" ),cons(NIL,NIL)),NIL)),cons(cons(cons(mk_symbol("equal?"),cons(cons(mk_symbol("caar"),cons(mk_symbol("alist"),NIL)),cons(mk_symbol("key"),NIL))),cons(cons(mk_symbol("alist-delete"),cons(cons(mk_symbol("cdr"),cons(mk_symbol("alist"),NIL)),cons(mk_symbol("key"),NIL))),NIL)),cons(cons(mk_symbol("else"),cons(cons(mk_symbol("cons"),cons(cons(mk_symbol("car"),cons(mk_symbol("alist"),NIL)),cons(cons(mk_symbol("alist-delete"),cons(cons(mk_symbol("cdr"),cons(mk_symbol("alist"),NIL)),cons(mk_symbol("key"),NIL))),NIL))),NIL)),NIL)))),NIL))),NIL))),cons(cons(mk_symbol("define"),cons(mk_symbol("alist-delete!"),cons(cons(mk_symbol("lambda"),cons(cons(mk_symbol("alist"),cons(mk_symbol("key"),NIL)),cons(cons(mk_symbol("cond"),cons(cons(cons(mk_symbol("null?"),cons(mk_symbol("alist"),NIL)),cons(cons( mk_symbol("quote" ),cons(NIL,NIL)),NIL)),cons(cons(cons(mk_symbol("equal?"),cons(cons(mk_symbol("caar"),cons(mk_symbol("alist"),NIL)),cons(mk_symbol("key"),NIL))),cons(cons(mk_symbol("cond"),cons(cons(cons(mk_symbol("null?"),cons(cons(mk_symbol("cdr"),cons(mk_symbol("alist"),NIL)),NIL)),cons(cons( mk_symbol("quote" ),cons(NIL,NIL)),NIL)),cons(cons(mk_symbol("else"),cons(cons(mk_symbol("set-car!"),cons(mk_symbol("alist"),cons(cons(mk_symbol("cadr"),cons(mk_symbol("alist"),NIL)),NIL))),cons(cons(mk_symbol("set-cdr!"),cons(mk_symbol("alist"),cons(cons(mk_symbol("cddr"),cons(mk_symbol("alist"),NIL)),NIL))),cons(cons(mk_symbol("alist-delete"),cons(mk_symbol("alist"),cons(mk_symbol("key"),NIL))),cons(mk_symbol("alist"),NIL))))),NIL))),NIL)),cons(cons(mk_symbol("else"),cons(cons(mk_symbol("set-cdr!"),cons(mk_symbol("alist"),cons(cons(mk_symbol("alist-delete"),cons(cons(mk_symbol("cdr"),cons(mk_symbol("alist"),NIL)),cons(mk_symbol("key"),NIL))),NIL))),cons(mk_symbol("alist"),NIL))),NIL)))),NIL))),NIL))),cons(cons(mk_symbol("define"),cons(mk_symbol("last-pair"),cons(mk_operation(LOC_LASTPAIR,&NIL),NIL))),NIL)))),NIL))))), environment);
return return_value;
}
